name = "Mandapam"
license = "MIT"
licenselink = "https://github.com/ananthb/mandapam-theme/blob/main/LICENSE"
description = "A photo-led, WhatsApp-first Hugo theme for wedding halls, auditoriums and event venues"
homepage = "https://github.com/ananthb/mandapam-theme"
min_version = "0.128.0"

[author]
  name = "Ananth Bhaskararaman"
  homepage = "https://github.com/ananthb"
